### ISSUE TITLE
Print out more event types.

### ISSUE THREAD

**Issue by poljar** [poljar/weechat-matrix-rs#2]
The [RoomBuffer](https://github.com/poljar/weechat-matrix-rs/blob/master/src/room_buffer.rs) struct receives all the incoming events. It currently only prints out and handles properly a couple of events.

The event formatting should probably go into a separate file and should consist of pure methods. Something in the spirit of the [message_renderer](https://github.com/poljar/weechat-matrix/blob/master/matrix/message_renderer.py#L26) file from the python script.

**Comment by vbrandl** [comment]
Would you mind explaining your thoughts on this?

I started on an idea myself: https://github.com/vbrandl/weechat-matrix-rs/blob/feature/event-rendering/src/render.rs

The idea is to have a `Renderable` trait and implement it for each event that should be rendered in weechat. In the example, I implemented `Renderable` for `MessageEvent` and `MemberEvent`.

Is this what you imagined?

**Comment by poljar** [comment]
Sure a trait works fine for this. Looks good, though be aware that the display name won't be available in the event, so we'll need to pass the display name which is contained in the user/room member. 

Using the user id for now is fine.

Another thing, please add at least some docs to the module and trait.

**Comment by vbrandl** [comment]
So the `render` function should take the display name as a Parameter?

As for documentation: sure that was just a fist draft to check if you agree with the overall design

**Comment by poljar** [comment]
Yeah think that this would make the most sense and not bloat the room buffer file like in the Python version.

**Comment by poljar** [comment]
We now render most events, if some are still missing a separate issue should be opened.
